"""PTHAdventures - Choose-your-own-adventure password cracking education."""

from spellengine.adventures.models import (
    Campaign,
    Chapter,
    Choice,
    Encounter,
    EncounterType,
    GameOverOptions,
    OutcomeType,
    PlayerState,
)
from spellengine.adventures.state import AdventureState
from spellengine.adventures.loader import load_campaign
from spellengine.adventures.achievements import (
    Achievement,
    AchievementCategory,
    AchievementManager,
    AchievementRarity,
    TriggerType,
    UnlockedAchievement,
    ACHIEVEMENT_LIBRARY,
    create_achievement_manager,
    format_achievement_notification,
    get_achievement_by_id,
    get_achievements_by_trigger,
)
from spellengine.adventures.hashlib_designed import (
    DesignedHash,
    HashCategory,
    ALL_TIERS,
    DREAD_CITADEL_HASH_MAP,
    find_hash,
    get_all_hashes,
    get_campaign_hash,
    get_hashes_by_category,
    get_hashes_by_tier,
    get_hashes_by_type,
    get_library_stats,
    iterate_by_tier,
)
from spellengine.adventures.experience_grading import (
    # Enums
    GradingDimension,
    PacingRating,
    EmotionalBeat,
    SequenceRole,
    # Score Models
    DimensionScore,
    EncounterGrade,
    ChapterGrade,
    CampaignGrade,
    # Sequencing
    SequencingPrinciple,
    SEQUENCING_PRINCIPLES,
    # Functions
    grade_encounter,
    grade_chapter,
    grade_campaign,
    generate_grade_report,
    # Dread Citadel
    DREAD_CITADEL_GRADES,
    get_dread_citadel_grades,
    create_dread_citadel_campaign_grade,
    create_grading_manifest,
)
from spellengine.adventures.dice import (
    DieType,
    RollResult,
    roll,
    roll_expression,
    advantage,
    disadvantage,
    animated_roll,
    skill_check,
    percentile_check,
    random_encounter_check,
    loot_roll,
    dramatic_d20,
    roll_stats,
    coin_flip,
    oracle,
)
from spellengine.adventures.assets import (
    AssetLoader,
    ArtStyle,
    DEFAULT_ART_STYLE,
)

__all__ = [
    # Models
    "Campaign",
    "Chapter",
    "Choice",
    "Encounter",
    "EncounterType",
    "GameOverOptions",
    "OutcomeType",
    "PlayerState",
    # State
    "AdventureState",
    # Loader
    "load_campaign",
    # Achievements
    "Achievement",
    "AchievementCategory",
    "AchievementManager",
    "AchievementRarity",
    "TriggerType",
    "UnlockedAchievement",
    "ACHIEVEMENT_LIBRARY",
    "create_achievement_manager",
    "format_achievement_notification",
    "get_achievement_by_id",
    "get_achievements_by_trigger",
    # Designed Hash Library
    "DesignedHash",
    "HashCategory",
    "ALL_TIERS",
    "DREAD_CITADEL_HASH_MAP",
    "find_hash",
    "get_all_hashes",
    "get_campaign_hash",
    "get_hashes_by_category",
    "get_hashes_by_tier",
    "get_hashes_by_type",
    "get_library_stats",
    "iterate_by_tier",
    # Experience Grading
    "GradingDimension",
    "PacingRating",
    "EmotionalBeat",
    "SequenceRole",
    "DimensionScore",
    "EncounterGrade",
    "ChapterGrade",
    "CampaignGrade",
    "SequencingPrinciple",
    "SEQUENCING_PRINCIPLES",
    "grade_encounter",
    "grade_chapter",
    "grade_campaign",
    "generate_grade_report",
    "DREAD_CITADEL_GRADES",
    "get_dread_citadel_grades",
    "create_dread_citadel_campaign_grade",
    "create_grading_manifest",
    # Dice
    "DieType",
    "RollResult",
    "roll",
    "roll_expression",
    "advantage",
    "disadvantage",
    "animated_roll",
    "skill_check",
    "percentile_check",
    "random_encounter_check",
    "loot_roll",
    "dramatic_d20",
    "roll_stats",
    "coin_flip",
    "oracle",
    # Assets
    "AssetLoader",
    "ArtStyle",
    "DEFAULT_ART_STYLE",
]
